# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver_path="..//geckodriver.exe"

class TestDemo():
  def setup_method(self):
    self.driver = webdriver.Firefox(executable_path=driver_path)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_demo(self):
    self.driver.get("https://www7.fdic.gov/sod/sodMarketBank.asp?barItem=2")
    self.driver.set_window_size(550, 692)
    self.driver.find_element(By.ID, "tdTabProForma").click()
    self.driver.find_element(By.CSS_SELECTOR, "#divtdTabProForma tr:nth-child(2) > td > label").click()
    element = self.driver.find_element(By.ID, "PFMSADepositDate")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "PFMSADepositDate")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "PFMSADepositDate")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "PFMSADepositDate").click()
    dropdown = self.driver.find_element(By.ID, "PFMSADepositDate")
    dropdown.find_element(By.XPATH, "//option[. = 'June 30, 2004']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#PFMSADepositDate > option:nth-child(17)").click()
  
if __name__ == '__main__':
    test = TestDemo()
    test.setup_method()
    test.test_demo()